# Generated by Django 3.0.3 on 2020-02-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada_app', '0002_auto_20200216_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='fotos'),
        ),
    ]
