# Generated by Django 3.0.3 on 2020-02-26 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada_app', '0003_visita_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fecha_pub',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
            preserve_default=False,
        ),
    ]
