# Generated by Django 3.0.3 on 2020-02-26 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada_app', '0004_visita_fecha_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='visitas_granada_app.Visita'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='foto',
            field=models.ImageField(default='fotos/default.png', upload_to=''),
        ),
    ]
