# Generated by Django 3.0.3 on 2020-03-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada_app', '0006_auto_20200319_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='foto',
            field=models.ImageField(default='fotos/default.png', upload_to='fotos/'),
        ),
    ]
