# Generated by Django 3.0.3 on 2020-04-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada_app', '0008_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='lat',
            field=models.IntegerField(default=37.196459),
        ),
        migrations.AddField(
            model_name='visita',
            name='lon',
            field=models.IntegerField(default=-3.6261883),
        ),
    ]
